DISCORD_WEBHOOK_URL = "discord_webhook_url"
LINE_CHANNEL_SECRET = "line_channel_secret"
LINE_CHANNEL_ACCESS_TOKEN = "line_channel_access_token"
MONGODB_URI = "mongodb_uri"
MONGODB_DATABASE = "mongodb_database"
MONGODB_COLLECTION_LINE_CONVERSATIONS = "mongodb_collection_line_conversations"
MONGODB_COLLECTION_LINE_MESSAGES = "mongodb_collection_line_messages"