openapi: "3.0.1"
info:
  title: "botio_rest_api"
  version: "2023-06-23T16:06:20Z"
servers:
  - url: "https://uwjxbrtk8b.execute-api.ap-southeast-1.amazonaws.com/{basePath}"
    variables:
      basePath:
        default: "dev"
paths:
  /shops/{shop_id}/facebook/{page_id}/conversations/{conversation_id}:
    get:
      responses:
        "200":
          description: successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StandardConversationWrapper"
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "conversation_id"
          in: "path"
          required: true
          schema:
            type: "string"
    patch:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "conversation_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /shops/{shop_id}/all/conversations:
    get:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /shops/{shop_id}/facebook/{page_id}/conversations/{conversation_id}/messages:
    get:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "conversation_id"
          in: "path"
          required: true
          schema:
            type: "string"
    post:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "conversation_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /shops/{shop_id}/line/{page_id}/webhook:
    post:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /shops/{shop_id}/facebook/{page_id}:
    get:
      responses:
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /shops/{shop_id}/instagram/{page_id}/conversations:
    get:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /shops/{shop_id}/facebook/{page_id}/webhook:
    get:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
    post:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /shops/{shop_id}/instagram/{page_id}/webhook:
    get:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
    post:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /shops/{shop_id}/instagram/{page_id}/conversations/{conversation_id}/messages:
    get:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "conversation_id"
          in: "path"
          required: true
          schema:
            type: "string"
    post:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "conversation_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /shops/{shop_id}/facebook/{page_id}/conversations:
    get:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /shops/{shop_id}/line/{page_id}:
    get:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /shops/{shop_id}/line/{page_id}/conversations/{conversation_id}/messages:
    get:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "conversation_id"
          in: "path"
          required: true
          schema:
            type: "string"
    post:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "conversation_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /shops/{shop_id}/instagram/{page_id}:
    get:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /shops/{shop_id}/line/{page_id}/conversations:
    get:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /shops/{shop_id}/instagram/{page_id}/conversations/{conversation_id}:
    get:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "conversation_id"
          in: "path"
          required: true
          schema:
            type: "string"
    patch:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "conversation_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /shops/{shop_id}/line/{page_id}/conversations/{conversation_id}:
    get:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "conversation_id"
          in: "path"
          required: true
          schema:
            type: "string"
    patch:
      responses:
        "200":
          description: successful
      parameters:
        - name: "shop_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "page_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "conversation_id"
          in: "path"
          required: true
          schema:
            type: "string"
components:
  schemas:
    StandardMessage:
      required:
        - shopID
        - platform
        - pageID
        - conversationID
        - messageID
        - timestamp
        - source
        - message
        - attachments
        - isDeleted
      type: object
      properties:
        shopID:
          type: string
        platform:
          type: string
        pageID:
          type: string
        conversationID:
          type: string
        messageID:
          type: string
        timestamp:
          type: integer
          format: int64
        source:
          $ref: "#/components/schemas/Source"
        message:
          type: string
        attachments:
          type: array
          items:
            $ref: "#/components/schemas/Attachment"
        replyTo:
          $ref: "#/components/schemas/RepliedMessage"
        isDeleted:
          type: boolean
    Source:
      required:
        - userID
        - userType
      type: object
      properties:
        userID:
          type: string
        userType:
          type: string
    Attachment:
      required:
        - attachmentType
        - payload
      type: object
      properties:
        attachmentType:
          type: string
        payload:
          $ref: "#/components/schemas/Payload"
    Payload:
      required:
        - src
      type: object
      properties:
        src:
          type: string
    RepliedMessage:
      required:
        - messageID
      type: object
      properties:
        messageID:
          type: string
    StandardConversation:
      required:
        - shopID
        - platform
        - pageID
        - conversationID
        - conversationPic
        - updatedTime
        - participants
        - lastActivity
        - unread
      type: object
      properties:
        shopID:
          type: string
        platform:
          type: string
        pageID:
          type: string
        conversationID:
          type: string
        conversationPic:
          $ref: "#/components/schemas/Payload"
        updatedTime:
          type: integer
          format: int64
        participants:
          type: array
          items:
            $ref: "#/components/schemas/Participant"
        lastActivity:
          type: string
        unread:
          type: integer
    Participant:
      required:
        - userID
        - username
        - profilePic
      type: object
      properties:
        userID:
          type: string
        username:
          type: string
        profilePic:
          $ref: "#/components/schemas/Payload"
    StandardConversationList:
      required:
        - conversations
      type: object
      properties:
        conversations:
          type: array
          items:
            $ref: "#/components/schemas/StandardConversation"
    StandardMessageList:
      required:
        - messages
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/StandardMessage"
    StandardConversationWrapper:
      required:
        - conversation
      type: object
      properties:
        conversation:
          $ref: "#/components/schemas/StandardConversation"
    StandardMessageWrapper:
      required:
        - message
      type: object
      properties:
        message:
          $ref: "#/components/schemas/StandardMessage"